config/routes.rb
Rails.application.routes.draw do
  resources :olympic_medals

   root 'olympic_medals#index'

end

app/models/olympic_medal.rb
class OlympicMedal < ActiveRecord::Base
    
    #Use a validation with the :inclusion argument to insure that medal_type is "gold", "silver", or "bronze".
    # Added below for 10.D and 10.E
    validates :medal_type, :inclusion => { :in => ["gold", "silver", "bronze"] }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/olympic_medals_controller.rb
class OlympicMedalsController < ApplicationController
  before_action :set_olympic_medal, only: [:show, :edit, :update, :destroy]

  # GET /olympic_medals
  # GET /olympic_medals.json
  def index
    @olympic_medals = OlympicMedal.all
  end

  # GET /olympic_medals/1
  # GET /olympic_medals/1.json
  def show
  end

  # GET /olympic_medals/new
  def new
    @olympic_medal = OlympicMedal.new
  end

  # GET /olympic_medals/1/edit
  def edit
  end

  # POST /olympic_medals
  # POST /olympic_medals.json
  def create
    @olympic_medal = OlympicMedal.new(olympic_medal_params)

    respond_to do |format|
      if @olympic_medal.save
        format.html { redirect_to @olympic_medal, notice: 'Olympic medal was successfully created.' }
        format.json { render :show, status: :created, location: @olympic_medal }
      else
        format.html { render :new }
        format.json { render json: @olympic_medal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /olympic_medals/1
  # PATCH/PUT /olympic_medals/1.json
  def update
    respond_to do |format|
      if @olympic_medal.update(olympic_medal_params)
        format.html { redirect_to @olympic_medal, notice: 'Olympic medal was successfully updated.' }
        format.json { render :show, status: :ok, location: @olympic_medal }
      else
        format.html { render :edit }
        format.json { render json: @olympic_medal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /olympic_medals/1
  # DELETE /olympic_medals/1.json
  def destroy
    @olympic_medal.destroy
    respond_to do |format|
      format.html { redirect_to olympic_medals_url, notice: 'Olympic medal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_olympic_medal
      @olympic_medal = OlympicMedal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def olympic_medal_params
      params.require(:olympic_medal).permit(:athlete_name, :event, :country, :medal_type, :event_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/olympic_medals_helper.rb
module OlympicMedalsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/olympic_medals/_form.html.erb
<%= form_for(@olympic_medal) do |f| %>
  <% if @olympic_medal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@olympic_medal.errors.count, "error") %> prohibited this olympic_medal from being saved:</h2>

      <ul>
      <% @olympic_medal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :athlete_name %><br>
    <!-- Updated for Question 10.C to make athlete name non-empty-->
    <%= f.text_field :athlete_name, :required => true%>
  </div>
  <div class="field">
    <%= f.label :event %><br>
    <%= f.text_field :event %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <!-- Updated for Question 10.C to make country name non-empty-->
    <%= f.text_field :country, :required => true%>
  </div>
  <div class="field">
    <%= f.label :medal_type %><br>
    <%= f.text_field :medal_type %>
  </div>
  <div class="field">
    <%= f.label :event_date %><br>
    <!-- Updated below line for question 10.B -->
    <%= f.date_select :event_date,{:selected =>2012} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/olympic_medals/edit.html.erb
<h1>Editing Olympic Medal</h1>

<%= render 'form' %>

<%= link_to 'Show', @olympic_medal %> |
<%= link_to 'Back', olympic_medals_path %>

app/views/olympic_medals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Olympic Medals</h1>

<table>
  <thead>
    <tr>
      <th>Athlete name</th>
      <th>Event</th>
      <th>Country</th>
      <th>Medal type</th>
      <th>Event date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @olympic_medals.each do |olympic_medal| %>
      <tr>
        <td><%= olympic_medal.athlete_name %></td>
        <td><%= olympic_medal.event %></td>
        <td><%= olympic_medal.country %></td>
        <td><%= olympic_medal.medal_type %></td>
        <td><%= olympic_medal.event_date %></td>
        <td><%= link_to 'Show', olympic_medal %></td>
        <td><%= link_to 'Edit', edit_olympic_medal_path(olympic_medal) %></td>
        <td><%= link_to 'Destroy', olympic_medal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Olympic medal', new_olympic_medal_path %>

app/views/olympic_medals/new.html.erb
<h1>New Olympic Medal</h1>

<%= render 'form' %>

<%= link_to 'Back', olympic_medals_path %>

app/views/olympic_medals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Athlete name:</strong>
  <%= @olympic_medal.athlete_name %>
</p>

<p>
  <strong>Event:</strong>
  <%= @olympic_medal.event %>
</p>

<p>
  <strong>Country:</strong>
  <%= @olympic_medal.country %>
</p>

<p>
  <strong>Medal type:</strong>
  <%= @olympic_medal.medal_type %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @olympic_medal.event_date %>
</p>

<%= link_to 'Edit', edit_olympic_medal_path(@olympic_medal) %> |
<%= link_to 'Back', olympic_medals_path %>